### PR TITLE
Rewrite the get-latest-versions with python3

### PR DESCRIPTION
**Pull request by tristanlins**
Unfortunately python2 seems to have problems with proxies on ubuntu 16.04.
I'm not a python expert, this may be done easier or with python 2. But now it works for me :-D

### CODE REVIEW

**Comment by reiz** [comment]
@tristanlins I'm not a python guy. How is the distribution of Python3? Is installed by default on every Ubuntu instance? Maybe it makes sense to have 2 scripts, on with Python 2 and another one with Python 3. In the update script we could check which version of Python is available and depending on that we could use the correct `get-latest-versions` script.

**Comment by tristanlins** [comment]
I'm not a python guy as well, I just read the documentation and adopt the examples with the help of stackoverflow xD

**Comment by reiz** [comment]
Maybe @svogt can share his opinion with us about Python 3 :)

**Comment by reiz** [comment]
@tristanlins @svogt I close this ticket because @timgluz refactored the script that it works with pure shell and jq. Now we don't need Python anymore :) See pull request #8.

**Pull request closed without merging**
